FROM alpine:3.18

RUN apk --no-cache add \
    pcsc-lite \
    pcsc-lite-libs \
    pcsc-lite-dev \
    libusb-compat \
    libusb-compat-dev \
    gcc \
    make \
    musl-dev \
    git \
    linux-headers \
    pkgconf \
    cmake